name: HikariEssentials
version: '${project.version}'
main: lithium.hikariessentials.HikariTokens.HikariEssentialsToken
api-version: 1.19
load: STARTUP
authors: [HikariSpigot]
description: Hikari's Essentail Plugin
website: lithium-network.de


commands:
  tokens:
    aliases: [token, te]
  tadmin:
    description: tadmin main command.
  exchange:
    description: main token exchange command.
  balance:
    aliases: [balance, tokens]
  baltop:
    aliases: [topbal]
  pay:
    aliases: [give]
  toggle:
    aliases: [toggletoken]
  bank:
    description: bank system command
