name: HikariEssentials
version: '${project.version}'
main: lithium.hikariessentials.HikariEssentials
api-version: 1.19
load: STARTUP
authors: [HikariSpigot]
description: Hikari's Essentail Plugin
website: lithium-network.de
